-- MySQL Script generated by MySQL Workbench
-- Thu Nov  9 12:00:37 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema The witcher
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `The witcher` ;

-- -----------------------------------------------------
-- Schema The witcher
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `The witcher` ;
USE `The witcher` ;

-- -----------------------------------------------------
-- Table `The witcher`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `The witcher`.`User` (
  `id` VARCHAR(36) NOT NULL,
  `pseudonyme` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `mot de passe` VARCHAR(255) NULL,
  `ip` TEXT(1000) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `The witcher`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `The witcher`.`article` (
  `id` VARCHAR(36) NOT NULL,
  `titre` VARCHAR(255) NULL,
  `contenu` LONGTEXT NULL,
  `datetime` DATETIME NULL,
  `image` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `The witcher`.`commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `The witcher`.`commentaire` (
  `id` VARCHAR(36) NOT NULL,
  `contenu` TEXT(2000) NULL,
  `datetime` DATETIME NULL,
  `ip` TEXT(1000) NULL,
  `User_id` VARCHAR(36) NOT NULL,
  `article_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`, `User_id`, `article_id`),
  INDEX `fk_commentaire_User1_idx` (`User_id` ASC) VISIBLE,
  INDEX `fk_commentaire_article1_idx` (`article_id` ASC) VISIBLE,
  CONSTRAINT `fk_commentaire_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `The witcher`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commentaire_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `The witcher`.`article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `The witcher`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `The witcher`.`question` (
  `id` VARCHAR(36) NOT NULL,
  `titre` VARCHAR(255) NULL,
  `contenu` LONGTEXT NULL,
  `datetime` DATETIME NULL,
  `ip` TEXT(1000) NULL,
  `User_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`, `User_id`),
  INDEX `fk_question_User1_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_question_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `The witcher`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `The witcher`.`réponse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `The witcher`.`réponse` (
  `id` VARCHAR(36) NOT NULL,
  `contenu` LONGTEXT NULL,
  `datetime` DATETIME NULL,
  `ip` TEXT(1000) NULL,
  `question_id` VARCHAR(36) NOT NULL,
  `User_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`, `question_id`, `User_id`),
  INDEX `fk_réponse_question1_idx` (`question_id` ASC) VISIBLE,
  INDEX `fk_réponse_User1_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_réponse_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `The witcher`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_réponse_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `The witcher`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
